name: trivia_guru
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  logging: ^1.2.0
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  confetti: ^0.7.0
  blinking_text: ^1.0.0
  path_provider: ^2.1.2
  path: ^1.8.3
  get: ^4.6.6
  flutter_svg: ^2.0.10+1
  common_code:
    git:
      url: https://github.com/patishavir/common_code.git
      ref: dev    #branch name

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/questions/
    - assets/images/
    - assets/icons/
  fonts:
    - family: NovaSlim
      fonts:
        - asset: assets/fonts/NovaSlim-Regular.ttf
    - family: gadi-almog
      fonts:
        - asset: assets/fonts/gadi-almog-regular-aaa.otf